apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/canbo01/jenkins.git
    targetRevision: HEAD
    path: development
  destination:
    server: https://kubernetes.default.svc
    namespace: development