apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins-dev
spec:
  type: NodePort
  ports:
<<<<<<< HEAD:jenkins_service.yaml
    - port: 8080
      targetPort: 8080
      nodePort: 30000
=======
  - port: 80
    protocol: TCP
    targetPort: 8080
>>>>>>> 0b85d5e777f5252ddf5f58ddc771dcb2a17262f1:dev/jenkins_service.yaml
  selector:
    app: jenkins
	
---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: jenkins-dev
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins